### ISSUE TITLE
老哥，上一个版本怎么实现的（单片机）

### ISSUE THREAD

**Issue by zuoteamleader** [1998NOTF/CF_RedNameCheck#3]

**Comment by NOTF-API** [comment]
代码里不是可以获取到是否有红名吗？既然可以判断，把这个提交给单片机(通过显示一块白块在屏幕上，光敏电阻判断 或者直接通过串口告知单片机) 然后用单片机控制鼠标(需要改装鼠标) 即可

**Comment by NOTF-API** [comment]
现在那么多DMA，双机Ai的方式，你还找到了我这个冷门方法，只能说你方向走错了

**Comment by zuoteamleader** [comment]
好的👌🏻
